apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jnlp
      env:
        - name: CONTAINER_ENV_VAR
          value: jnlp
    - name: agent
      image: gcr.io/rpa-devops/jenkins-agent
      command:
        - sleep
      args:
        - 99d
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
    - name: odi
      image: gcr.io/rpa-devops/odi:12.2.1.3.2-SNAPSHOT
      ports:
        - containerPort: 1521
          name: database-port
        - containerPort: 20910
          name: agent-port
      tty: true
      resources:
        requests:
          cpu: "1"
          memory: "2Gi"
