apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jnlp
      env:
        - name: CONTAINER_ENV_VAR
          value: jnlp
    - name: agent
      image: gcr.io/rpa-devops/jenkins-agent
      command:
        - sleep
      args:
        - 99d
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
    - name: odi
      image: gcr.io/rpa-devops/odi:12.2.1.3.2-SNAPSHOT
      ports:
        - containerPort: 1521
          name: database-port
        - containerPort: 20910
          name: agent-port
      startupProbe:
        exec:
          command:
            - nc
            - localhost
            - 20910
            - <
            - /dev/null
        initialDelaySeconds: 300
        periodSeconds: 60
        failureThreshold: 30
      tty: true
      resources:
        requests:
          cpu: "1"
          memory: "2Gi"
